# Generated by Django 3.0.4 on 2020-06-03 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DptPublicos',
            new_name='DptPublico',
        ),
    ]
