# Generated by Django 3.0.4 on 2020-06-03 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20200603_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='status',
            field=models.CharField(blank=True, choices=[('AB', 'Aberta'), ('EM', 'Em Andamento'), ('FE', 'Fechada'), ('EA', 'Em Acompanhamento')], default='AB', help_text='Status Da Denuncia', max_length=2),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='nome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
