# Generated by Django 3.0.4 on 2020-06-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200603_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
