# Generated by Django 3.0.4 on 2020-03-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('data_nascimento', models.DateTimeField()),
                ('cep', models.IntegerField()),
            ],
        ),
    ]
