# Generated by Django 3.0.4 on 2020-03-21 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DptPublicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14)),
                ('tel', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=50)),
                ('numero', models.SmallIntegerField()),
                ('cep', models.SmallIntegerField()),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto_denuncia', models.TextField(max_length=1500)),
                ('denunciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User')),
                ('dpt_publico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DptPublicos')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Endereco')),
            ],
        ),
    ]
